name: PyInstaller Build

on:
  push:
    branches:
      - master  # Adjust the branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v2.1
        release_name: RDOTool 2.1
        draft: false
        prerelease: false

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: RDOTool.exe
        path: src/dist/RDOTool.exe 
